[package]
name = "test/custom-shell"
version = "0.2.0"
description = "Custom shell with node bridge + bash + coreutils"

[dependencies]
"sharrattj/coreutils" = "1.0.16"
"sharrattj/bash" = "*"

[[module]]
name = "node-bridge"
source = "node-bridge.wasm"
abi = "wasi"

[[command]]
name = "node"
module = "node-bridge"
runner = "wasi"
